'use client';

import Link from 'next/link';
import { useMemo, useState, useTransition } from 'react';
import { Activity, CheckCircle2, ChevronLeft, ChevronRight, Download, Eye, Loader2, RefreshCcw, Search, ShieldCheck, Stethoscope, Users, X } from 'lucide-react';
import { resetDoctorScans, setDoctorActive, setDoctorPlan } from './actions';
import { AdminLogoutButton } from './admin-logout-button';

export type AdminDoctor={id:string;clinic_name:string;doctor_name:string;email:string;phone:string|null;subscription_tier:'starter'|'growth'|'premium';total_scans_used:number;is_active:boolean;is_admin:boolean;plan_started_at:string|null;plan_expires_at:string|null};
type Metrics={total:number;starter:number;growth:number;premium:number;scans:number};
type GenerationUsage=readonly [string,number,number][];
const pageSize=10;
const formatDate=(value:string|null)=>value?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value)):'No expiry';

function DoctorRow({doctor,notify}:{doctor:AdminDoctor;notify:(message:string,type?:'success'|'error')=>void}){
  const [pending,startTransition]=useTransition();
  const run=(action:()=>Promise<void>,message:string)=>startTransition(async()=>{try{await action();notify(message)}catch(error){notify(error instanceof Error?error.message:'Action failed.','error')}});
  return <tr className="border-t border-[#0A4C95]/10 text-[#0A4C95] transition hover:bg-[#0A4C95]/[.035]">
    <td className="px-5 py-4"><Link href={`/admin/dashboard/doctors/${doctor.id}`} className="font-extrabold underline-offset-4 hover:text-[#F37021] hover:underline">{doctor.clinic_name}</Link><p className="mt-1 text-xs text-[#0A4C95]/65">{doctor.doctor_name}</p></td>
    <td className="px-5 py-4 text-sm">{doctor.email||'—'}</td><td className="px-5 py-4 text-sm">{doctor.phone||'—'}</td>
    <td className="px-5 py-4"><select aria-label={`Plan for ${doctor.clinic_name}`} disabled={pending||doctor.is_admin} value={doctor.subscription_tier} onChange={event=>run(()=>setDoctorPlan(doctor.id,event.target.value),`${doctor.clinic_name} moved to ${event.target.value}.`)} className="rounded-lg border border-[#0A4C95]/25 bg-white px-3 py-2 text-xs font-bold capitalize text-[#0A4C95] outline-none focus:border-[#F37021]">{['starter','growth','premium'].map(tier=><option key={tier}>{tier}</option>)}</select><p className="mt-1 text-[10px] font-semibold text-[#0A4C95]/60">{doctor.subscription_tier==='starter'?'Free tier':`Expires ${formatDate(doctor.plan_expires_at)}`}</p></td>
    <td className="px-5 py-4 text-center font-black">{doctor.total_scans_used.toLocaleString()}</td>
    <td className="px-5 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${doctor.is_active?'bg-[#0A4C95] text-white':'bg-[#F37021] text-white'}`}>{doctor.is_active?'Active':'Suspended'}</span></td>
    <td className="px-5 py-4"><div className="flex min-w-max items-center gap-2"><Link href={`/admin/dashboard/doctors/${doctor.id}`} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-[#0A4C95]/20 px-3 text-xs font-bold hover:border-[#F37021] hover:text-[#F37021]"><Eye size={14}/>Details</Link><button disabled={pending||doctor.is_admin} onClick={()=>run(()=>resetDoctorScans(doctor.id),`Current scan cycle reset for ${doctor.clinic_name}.`)} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg bg-[#0A4C95] px-3 text-xs font-bold text-white disabled:opacity-50">{pending?<Loader2 className="animate-spin" size={14}/>:<RefreshCcw size={14}/>}Reset cycle</button><button type="button" role="switch" aria-checked={doctor.is_active} disabled={pending||doctor.is_admin} onClick={()=>run(()=>setDoctorActive(doctor.id,!doctor.is_active),`${doctor.clinic_name} ${doctor.is_active?'suspended':'activated'}.`)} className={`relative h-7 w-12 rounded-full transition disabled:opacity-40 ${doctor.is_active?'bg-[#0A4C95]':'bg-[#F37021]'}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition-all ${doctor.is_active?'left-6':'left-1'}`}/></button></div></td>
  </tr>;
}

export function AdminDashboard({doctors,metrics,adminEmail,isSuperAdmin,generationUsage}:{doctors:AdminDoctor[];metrics:Metrics;adminEmail:string;isSuperAdmin:boolean;generationUsage:GenerationUsage}){
  const [query,setQuery]=useState('');const [page,setPage]=useState(1);const [toast,setToast]=useState<{message:string;type:'success'|'error'}|null>(null);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?doctors.filter(d=>d.clinic_name.toLowerCase().includes(q)||d.email.toLowerCase().includes(q)):doctors},[doctors,query]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),safePage=Math.min(page,pages),visible=filtered.slice((safePage-1)*pageSize,safePage*pageSize);
  const notify=(message:string,type:'success'|'error'='success')=>{setToast({message,type});window.setTimeout(()=>setToast(null),3500)};
  const cards=[[Users,'Total doctors',metrics.total],[Stethoscope,'Starter plans',metrics.starter],[Activity,'Growth plans',metrics.growth],[ShieldCheck,'Premium plans',metrics.premium],[RefreshCcw,'Current-cycle scans',metrics.scans]] as const;
  return <main className="min-h-screen bg-white text-[#0A4C95]"><div className="mx-auto max-w-[1500px] px-4 py-6 sm:px-8 sm:py-9">
    <header className="flex flex-col gap-4 border-b border-[#0A4C95]/15 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-[#F37021]"><ShieldCheck size={16}/>Vyapar Wallah Control Center</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Super Admin Dashboard</h1><p className="mt-2 text-sm text-[#0A4C95]/65">Secure platform operations, subscriptions and clinic access.</p></div><div className="flex flex-col items-stretch gap-2 sm:items-end"><div className="rounded-xl border border-[#0A4C95]/15 bg-[#0A4C95]/[.035] px-4 py-3 text-right"><p className="text-[10px] font-bold uppercase tracking-widest text-[#F37021]">Authenticated admin</p><p className="mt-1 text-sm font-semibold">{adminEmail}</p></div><AdminLogoutButton/></div></header>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([Icon,label,value],index)=><div key={label} className="rounded-2xl border border-[#0A4C95]/15 bg-white p-5 shadow-lg shadow-[#0A4C95]/5"><Icon size={21} className={index%2?'text-[#F37021]':'text-[#0A4C95]'}/><p className="mt-5 text-3xl font-black">{value.toLocaleString()}</p><p className="mt-1 text-xs font-bold uppercase tracking-wider text-[#0A4C95]/60">{label}</p>{isSuperAdmin&&<a href="/api/admin/reports/scans" download className="mt-4 inline-flex min-h-9 w-full items-center justify-center gap-1.5 rounded-lg bg-[#0A4C95] px-3 text-xs font-black text-white transition hover:bg-[#F37021]"><Download size={14}/>Download Report</a>}</div>)}</section>
    {isSuperAdmin&&<section className="mt-5 grid gap-3 sm:grid-cols-3">{generationUsage.map(([label,value,cap])=><div key={label} className="rounded-2xl border border-[#0A4C95]/15 bg-white p-4 shadow-lg shadow-[#0A4C95]/5"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#0A4C95]/50">{label}</p><p className="mt-2 text-2xl font-black tabular-nums">{value}/{cap}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#0A4C95]/10"><div className="h-full rounded-full bg-[#F37021]" style={{width:`${Math.min(100,(value/cap)*100)}%`}}/></div></div>)}</section>}
    <section className="mt-6 overflow-hidden rounded-2xl border border-[#0A4C95]/15 bg-white shadow-xl shadow-[#0A4C95]/5"><div className="flex flex-col gap-4 border-b border-[#0A4C95]/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-extrabold">Doctors & clinics</h2><p className="mt-1 text-sm text-[#0A4C95]/60">Click a clinic for complete details and daily analytics.</p></div><label className="relative block w-full sm:max-w-sm"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search clinic or email…" className="h-11 w-full rounded-xl border border-[#0A4C95]/20 bg-white pl-10 pr-4 text-sm outline-none placeholder:text-[#0A4C95]/40 focus:border-[#F37021]"/></label></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left"><thead className="bg-[#0A4C95] text-[10px] font-black uppercase tracking-wider text-white"><tr>{['Clinic / doctor','Doctor email','Phone','Plan & expiry','Cycle scans','Status','Controls'].map(label=><th key={label} className="px-5 py-3">{label}</th>)}</tr></thead><tbody>{visible.map(doctor=><DoctorRow key={doctor.id} doctor={doctor} notify={notify}/>)}</tbody></table>{!visible.length&&<div className="px-5 py-16 text-center text-sm text-[#0A4C95]/60">No doctors match that search.</div>}</div>
      <div className="flex items-center justify-between border-t border-[#0A4C95]/10 px-5 py-4 text-xs text-[#0A4C95]/65"><span>Showing {visible.length} of {filtered.length} doctors</span><div className="flex items-center gap-2"><button disabled={safePage===1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="grid h-9 w-9 place-items-center rounded-lg border border-[#0A4C95]/20 disabled:opacity-30"><ChevronLeft size={16}/></button><span className="px-2 font-bold">{safePage} / {pages}</span><button disabled={safePage===pages} onClick={()=>setPage(p=>Math.min(pages,p+1))} className="grid h-9 w-9 place-items-center rounded-lg border border-[#0A4C95]/20 disabled:opacity-30"><ChevronRight size={16}/></button></div></div>
    </section>
  </div>{toast&&<div role="status" className={`fixed bottom-5 right-5 flex max-w-sm items-center gap-3 rounded-xl px-4 py-3 text-sm font-bold text-white shadow-2xl ${toast.type==='success'?'bg-[#0A4C95]':'bg-[#F37021]'}`}>{toast.type==='success'?<CheckCircle2 size={18}/>:<X size={18}/>}<span>{toast.message}</span></div>}</main>;
}
